version: '3'
services:
  plugin:
    image: anybox/buttervolume:2.0
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - "1122"
    volumes:
      - /var/lib/buttervolume:/var/lib/buttervolume
      - /run/docker/plugins:/run/docker/plugins
      - ./config:/etc/buttervolume
      - buttervolume_ssh:/root/.ssh

volumes:
  buttervolume_config:
  buttervolume_ssh:
