version: '2.1'
services:
  consul:
    environment:
      CONSUL_BIND_INTERFACE: wlan0
    command: ["agent", "-dev", "-ui"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ./deploy:/deploy
      - ./caddy/conf/:/consul/template/caddy/
      - ./haproxy/conf/:/consul/template/haproxy/
