version: '2.1'
services:

  caddy:
    build: caddy
    restart: unless-stopped
    volumes:
      - caddy_ssl:/root/.caddy
      - caddy_log:/var/log
      - ./caddy/conf/:/etc/caddy
    # Once #9710 (config logging options in docker/daemon.json) is deployed,
    # those logging options can be removed
    logging:
      options:
        "max-size": "3m"
        "max-file": "5"
        labels: "format,reseau,ets,service"
    labels:
      format: "caddy"
      reseau: "all"
      ets: "all"
      service: "caddy"

  haproxy:
    image: haproxy:1.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1443:1443"
      - "2222:22"
    volumes:
      - ./haproxy/conf/:/usr/local/etc/haproxy/

  consul:
    build: consul
    depends_on:
      - caddy
      - haproxy
    restart: unless-stopped
    network_mode: host
    command: ["agent", "-server", "-retry-join=10.91.151.183", "-retry-join=10.91.210.58", "-retry-join=10.91.210.59", "-retry-join=10.91.209.207", "-bootstrap-expect=3", "-ui"]
    environment:
        CONSUL_LOCAL_CONFIG: '{
            "skip_leave_on_interrupt": true,
            "watches": [{
                "type": "event",
                "handler": "/handler.py"}]
            }'
        CONSUL_BIND_INTERFACE: enp1s0f1
    volumes:
      - consul_docker_cfg:/home/consul/.docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ~/deploy:/deploy
      - ./caddy/conf/:/consul/template/caddy/
      - ./haproxy/conf/:/consul/template/haproxy/

volumes:
  caddy_log:
    driver: btrfs
  caddy_ssl:
    driver: btrfs
  consul_docker_cfg:
    driver: btrfs
