version: '2.1'
services:
  server:
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
        CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        COREOS_PRIVATE_IPV4: ${COREOS_PRIVATE_IPV4}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
