version: '2.1'
services:
  server:
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
        CONSUL_LOCAL_CONFIG: '{
            "skip_leave_on_interrupt": true,
            "watches": [{
                "type": "event",
                "handler": "/handler.py"}]
            }'
        CONSUL_BIND_INTERFACE: enp1s0f1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ~/deploy:/deploy
